/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Certification: typeof import('./src/components/Certification.vue')['default']
    Feature: typeof import('./src/components/Feature.vue')['default']
    Gauge: typeof import('./src/components/Gauge.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HorizontalBar: typeof import('./src/components/HorizontalBar.vue')['default']
    HorizontalBarChart: typeof import('./src/components/HorizontalBarChart.vue')['default']
    InfoItem: typeof import('./src/components/InfoItem.vue')['default']
    InfoTooltip: typeof import('./src/components/InfoTooltip.vue')['default']
    Log: typeof import('./src/components/Log.vue')['default']
    Project: typeof import('./src/components/Project.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    SkillItem: typeof import('./src/components/SkillItem.vue')['default']
    Stat: typeof import('./src/components/Stat.vue')['default']
    Tag: typeof import('./src/components/Tag.vue')['default']
    TimelineItem: typeof import('./src/components/TimelineItem.vue')['default']
    Title: typeof import('./src/components/Title.vue')['default']
    VerticalBar: typeof import('./src/components/VerticalBar.vue')['default']
    VerticalBarChart: typeof import('./src/components/VerticalBarChart.vue')['default']
  }
}
